services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Slub\SlubEvents\:
        resource: '../Classes/*'

    Slub\SlubEvents\Domain\Validator\EventSubscriptionAllowedValidator:
        public: true
        shared: false

    Slub\SlubEvents\Domain\Validator\SubscriberValidator:
        public: true
        shared: false
